/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "4.4.2-0ubuntu0.22.04.1"
#endif /* AVUTIL_FFVERSION_H */
